# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-4.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidkamphausen/projects2/vm/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidkamphausen/projects2/vm/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-4.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-4.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidkamphausen/projects2/vm/src/CMakeFiles /Users/davidkamphausen/projects2/vm/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidkamphausen/projects2/vm/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vm

# Build rule for target.
vm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm
.PHONY : vm

# fast build rule for target.
vm/fast:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/build
.PHONY : vm/fast

vm.o: vm.cc.o
.PHONY : vm.o

# target to build an object file
vm.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm.cc.o
.PHONY : vm.cc.o

vm.i: vm.cc.i
.PHONY : vm.i

# target to preprocess a source file
vm.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm.cc.i
.PHONY : vm.cc.i

vm.s: vm.cc.s
.PHONY : vm.s

# target to generate assembly for a file
vm.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm.cc.s
.PHONY : vm.cc.s

vm_arg.o: vm_arg.cc.o
.PHONY : vm_arg.o

# target to build an object file
vm_arg.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_arg.cc.o
.PHONY : vm_arg.cc.o

vm_arg.i: vm_arg.cc.i
.PHONY : vm_arg.i

# target to preprocess a source file
vm_arg.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_arg.cc.i
.PHONY : vm_arg.cc.i

vm_arg.s: vm_arg.cc.s
.PHONY : vm_arg.s

# target to generate assembly for a file
vm_arg.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_arg.cc.s
.PHONY : vm_arg.cc.s

vm_instruction.o: vm_instruction.cc.o
.PHONY : vm_instruction.o

# target to build an object file
vm_instruction.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_instruction.cc.o
.PHONY : vm_instruction.cc.o

vm_instruction.i: vm_instruction.cc.i
.PHONY : vm_instruction.i

# target to preprocess a source file
vm_instruction.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_instruction.cc.i
.PHONY : vm_instruction.cc.i

vm_instruction.s: vm_instruction.cc.s
.PHONY : vm_instruction.s

# target to generate assembly for a file
vm_instruction.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_instruction.cc.s
.PHONY : vm_instruction.cc.s

vm_memory.o: vm_memory.cc.o
.PHONY : vm_memory.o

# target to build an object file
vm_memory.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_memory.cc.o
.PHONY : vm_memory.cc.o

vm_memory.i: vm_memory.cc.i
.PHONY : vm_memory.i

# target to preprocess a source file
vm_memory.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_memory.cc.i
.PHONY : vm_memory.cc.i

vm_memory.s: vm_memory.cc.s
.PHONY : vm_memory.s

# target to generate assembly for a file
vm_memory.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_memory.cc.s
.PHONY : vm_memory.cc.s

vm_queues.o: vm_queues.cc.o
.PHONY : vm_queues.o

# target to build an object file
vm_queues.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_queues.cc.o
.PHONY : vm_queues.cc.o

vm_queues.i: vm_queues.cc.i
.PHONY : vm_queues.i

# target to preprocess a source file
vm_queues.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_queues.cc.i
.PHONY : vm_queues.cc.i

vm_queues.s: vm_queues.cc.s
.PHONY : vm_queues.s

# target to generate assembly for a file
vm_queues.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_queues.cc.s
.PHONY : vm_queues.cc.s

vm_regs.o: vm_regs.cc.o
.PHONY : vm_regs.o

# target to build an object file
vm_regs.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_regs.cc.o
.PHONY : vm_regs.cc.o

vm_regs.i: vm_regs.cc.i
.PHONY : vm_regs.i

# target to preprocess a source file
vm_regs.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_regs.cc.i
.PHONY : vm_regs.cc.i

vm_regs.s: vm_regs.cc.s
.PHONY : vm_regs.s

# target to generate assembly for a file
vm_regs.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_regs.cc.s
.PHONY : vm_regs.cc.s

vm_sim.o: vm_sim.cc.o
.PHONY : vm_sim.o

# target to build an object file
vm_sim.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_sim.cc.o
.PHONY : vm_sim.cc.o

vm_sim.i: vm_sim.cc.i
.PHONY : vm_sim.i

# target to preprocess a source file
vm_sim.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_sim.cc.i
.PHONY : vm_sim.cc.i

vm_sim.s: vm_sim.cc.s
.PHONY : vm_sim.s

# target to generate assembly for a file
vm_sim.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_sim.cc.s
.PHONY : vm_sim.cc.s

vm_thread.o: vm_thread.cc.o
.PHONY : vm_thread.o

# target to build an object file
vm_thread.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_thread.cc.o
.PHONY : vm_thread.cc.o

vm_thread.i: vm_thread.cc.i
.PHONY : vm_thread.i

# target to preprocess a source file
vm_thread.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_thread.cc.i
.PHONY : vm_thread.cc.i

vm_thread.s: vm_thread.cc.s
.PHONY : vm_thread.s

# target to generate assembly for a file
vm_thread.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_thread.cc.s
.PHONY : vm_thread.cc.s

vm_threads.o: vm_threads.cc.o
.PHONY : vm_threads.o

# target to build an object file
vm_threads.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_threads.cc.o
.PHONY : vm_threads.cc.o

vm_threads.i: vm_threads.cc.i
.PHONY : vm_threads.i

# target to preprocess a source file
vm_threads.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_threads.cc.i
.PHONY : vm_threads.cc.i

vm_threads.s: vm_threads.cc.s
.PHONY : vm_threads.s

# target to generate assembly for a file
vm_threads.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_threads.cc.s
.PHONY : vm_threads.cc.s

vm_types.o: vm_types.cc.o
.PHONY : vm_types.o

# target to build an object file
vm_types.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_types.cc.o
.PHONY : vm_types.cc.o

vm_types.i: vm_types.cc.i
.PHONY : vm_types.i

# target to preprocess a source file
vm_types.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_types.cc.i
.PHONY : vm_types.cc.i

vm_types.s: vm_types.cc.s
.PHONY : vm_types.s

# target to generate assembly for a file
vm_types.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_types.cc.s
.PHONY : vm_types.cc.s

vm_vm.o: vm_vm.cc.o
.PHONY : vm_vm.o

# target to build an object file
vm_vm.cc.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_vm.cc.o
.PHONY : vm_vm.cc.o

vm_vm.i: vm_vm.cc.i
.PHONY : vm_vm.i

# target to preprocess a source file
vm_vm.cc.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_vm.cc.i
.PHONY : vm_vm.cc.i

vm_vm.s: vm_vm.cc.s
.PHONY : vm_vm.s

# target to generate assembly for a file
vm_vm.cc.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/vm_vm.cc.s
.PHONY : vm_vm.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vm"
	@echo "... vm.o"
	@echo "... vm.i"
	@echo "... vm.s"
	@echo "... vm_arg.o"
	@echo "... vm_arg.i"
	@echo "... vm_arg.s"
	@echo "... vm_instruction.o"
	@echo "... vm_instruction.i"
	@echo "... vm_instruction.s"
	@echo "... vm_memory.o"
	@echo "... vm_memory.i"
	@echo "... vm_memory.s"
	@echo "... vm_queues.o"
	@echo "... vm_queues.i"
	@echo "... vm_queues.s"
	@echo "... vm_regs.o"
	@echo "... vm_regs.i"
	@echo "... vm_regs.s"
	@echo "... vm_sim.o"
	@echo "... vm_sim.i"
	@echo "... vm_sim.s"
	@echo "... vm_thread.o"
	@echo "... vm_thread.i"
	@echo "... vm_thread.s"
	@echo "... vm_threads.o"
	@echo "... vm_threads.i"
	@echo "... vm_threads.s"
	@echo "... vm_types.o"
	@echo "... vm_types.i"
	@echo "... vm_types.s"
	@echo "... vm_vm.o"
	@echo "... vm_vm.i"
	@echo "... vm_vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

