# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-4.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-4.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidkamphausen/projects2/vm/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidkamphausen/projects2/vm/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-4.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-4.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidkamphausen/projects2/vm/src/CMakeFiles /Users/davidkamphausen/projects2/vm/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidkamphausen/projects2/vm/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vm_api_test

# Build rule for target.
vm_api_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm_api_test
.PHONY : vm_api_test

# fast build rule for target.
vm_api_test/fast:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/build
.PHONY : vm_api_test/fast

#=============================================================================
# Target rules for targets named vm_run

# Build rule for target.
vm_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm_run
.PHONY : vm_run

# fast build rule for target.
vm_run/fast:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/build
.PHONY : vm_run/fast

#=============================================================================
# Target rules for targets named vm_type_sizes

# Build rule for target.
vm_type_sizes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm_type_sizes
.PHONY : vm_type_sizes

# fast build rule for target.
vm_type_sizes/fast:
	$(MAKE) -f CMakeFiles/vm_type_sizes.dir/build.make CMakeFiles/vm_type_sizes.dir/build
.PHONY : vm_type_sizes/fast

api/vm_api.o: api/vm_api.cc.o
.PHONY : api/vm_api.o

# target to build an object file
api/vm_api.cc.o:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api.cc.o
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api.cc.o
.PHONY : api/vm_api.cc.o

api/vm_api.i: api/vm_api.cc.i
.PHONY : api/vm_api.i

# target to preprocess a source file
api/vm_api.cc.i:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api.cc.i
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api.cc.i
.PHONY : api/vm_api.cc.i

api/vm_api.s: api/vm_api.cc.s
.PHONY : api/vm_api.s

# target to generate assembly for a file
api/vm_api.cc.s:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api.cc.s
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api.cc.s
.PHONY : api/vm_api.cc.s

api/vm_api_file.o: api/vm_api_file.cc.o
.PHONY : api/vm_api_file.o

# target to build an object file
api/vm_api_file.cc.o:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_file.cc.o
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api_file.cc.o
.PHONY : api/vm_api_file.cc.o

api/vm_api_file.i: api/vm_api_file.cc.i
.PHONY : api/vm_api_file.i

# target to preprocess a source file
api/vm_api_file.cc.i:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_file.cc.i
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api_file.cc.i
.PHONY : api/vm_api_file.cc.i

api/vm_api_file.s: api/vm_api_file.cc.s
.PHONY : api/vm_api_file.s

# target to generate assembly for a file
api/vm_api_file.cc.s:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_file.cc.s
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/api/vm_api_file.cc.s
.PHONY : api/vm_api_file.cc.s

api/vm_api_test.o: api/vm_api_test.cc.o
.PHONY : api/vm_api_test.o

# target to build an object file
api/vm_api_test.cc.o:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_test.cc.o
.PHONY : api/vm_api_test.cc.o

api/vm_api_test.i: api/vm_api_test.cc.i
.PHONY : api/vm_api_test.i

# target to preprocess a source file
api/vm_api_test.cc.i:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_test.cc.i
.PHONY : api/vm_api_test.cc.i

api/vm_api_test.s: api/vm_api_test.cc.s
.PHONY : api/vm_api_test.s

# target to generate assembly for a file
api/vm_api_test.cc.s:
	$(MAKE) -f CMakeFiles/vm_api_test.dir/build.make CMakeFiles/vm_api_test.dir/api/vm_api_test.cc.s
.PHONY : api/vm_api_test.cc.s

vm_arg.o: vm_arg.cc.o
.PHONY : vm_arg.o

# target to build an object file
vm_arg.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_arg.cc.o
.PHONY : vm_arg.cc.o

vm_arg.i: vm_arg.cc.i
.PHONY : vm_arg.i

# target to preprocess a source file
vm_arg.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_arg.cc.i
.PHONY : vm_arg.cc.i

vm_arg.s: vm_arg.cc.s
.PHONY : vm_arg.s

# target to generate assembly for a file
vm_arg.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_arg.cc.s
.PHONY : vm_arg.cc.s

vm_asm.o: vm_asm.cc.o
.PHONY : vm_asm.o

# target to build an object file
vm_asm.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_asm.cc.o
.PHONY : vm_asm.cc.o

vm_asm.i: vm_asm.cc.i
.PHONY : vm_asm.i

# target to preprocess a source file
vm_asm.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_asm.cc.i
.PHONY : vm_asm.cc.i

vm_asm.s: vm_asm.cc.s
.PHONY : vm_asm.s

# target to generate assembly for a file
vm_asm.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_asm.cc.s
.PHONY : vm_asm.cc.s

vm_config.o: vm_config.cc.o
.PHONY : vm_config.o

# target to build an object file
vm_config.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_config.cc.o
.PHONY : vm_config.cc.o

vm_config.i: vm_config.cc.i
.PHONY : vm_config.i

# target to preprocess a source file
vm_config.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_config.cc.i
.PHONY : vm_config.cc.i

vm_config.s: vm_config.cc.s
.PHONY : vm_config.s

# target to generate assembly for a file
vm_config.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_config.cc.s
.PHONY : vm_config.cc.s

vm_encoding.o: vm_encoding.cc.o
.PHONY : vm_encoding.o

# target to build an object file
vm_encoding.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_encoding.cc.o
.PHONY : vm_encoding.cc.o

vm_encoding.i: vm_encoding.cc.i
.PHONY : vm_encoding.i

# target to preprocess a source file
vm_encoding.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_encoding.cc.i
.PHONY : vm_encoding.cc.i

vm_encoding.s: vm_encoding.cc.s
.PHONY : vm_encoding.s

# target to generate assembly for a file
vm_encoding.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_encoding.cc.s
.PHONY : vm_encoding.cc.s

vm_instruction.o: vm_instruction.cc.o
.PHONY : vm_instruction.o

# target to build an object file
vm_instruction.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_instruction.cc.o
.PHONY : vm_instruction.cc.o

vm_instruction.i: vm_instruction.cc.i
.PHONY : vm_instruction.i

# target to preprocess a source file
vm_instruction.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_instruction.cc.i
.PHONY : vm_instruction.cc.i

vm_instruction.s: vm_instruction.cc.s
.PHONY : vm_instruction.s

# target to generate assembly for a file
vm_instruction.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_instruction.cc.s
.PHONY : vm_instruction.cc.s

vm_log.o: vm_log.cc.o
.PHONY : vm_log.o

# target to build an object file
vm_log.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_log.cc.o
.PHONY : vm_log.cc.o

vm_log.i: vm_log.cc.i
.PHONY : vm_log.i

# target to preprocess a source file
vm_log.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_log.cc.i
.PHONY : vm_log.cc.i

vm_log.s: vm_log.cc.s
.PHONY : vm_log.s

# target to generate assembly for a file
vm_log.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_log.cc.s
.PHONY : vm_log.cc.s

vm_memory.o: vm_memory.cc.o
.PHONY : vm_memory.o

# target to build an object file
vm_memory.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_memory.cc.o
.PHONY : vm_memory.cc.o

vm_memory.i: vm_memory.cc.i
.PHONY : vm_memory.i

# target to preprocess a source file
vm_memory.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_memory.cc.i
.PHONY : vm_memory.cc.i

vm_memory.s: vm_memory.cc.s
.PHONY : vm_memory.s

# target to generate assembly for a file
vm_memory.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_memory.cc.s
.PHONY : vm_memory.cc.s

vm_ops.o: vm_ops.cc.o
.PHONY : vm_ops.o

# target to build an object file
vm_ops.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_ops.cc.o
.PHONY : vm_ops.cc.o

vm_ops.i: vm_ops.cc.i
.PHONY : vm_ops.i

# target to preprocess a source file
vm_ops.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_ops.cc.i
.PHONY : vm_ops.cc.i

vm_ops.s: vm_ops.cc.s
.PHONY : vm_ops.s

# target to generate assembly for a file
vm_ops.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_ops.cc.s
.PHONY : vm_ops.cc.s

vm_pipe.o: vm_pipe.cc.o
.PHONY : vm_pipe.o

# target to build an object file
vm_pipe.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipe.cc.o
.PHONY : vm_pipe.cc.o

vm_pipe.i: vm_pipe.cc.i
.PHONY : vm_pipe.i

# target to preprocess a source file
vm_pipe.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipe.cc.i
.PHONY : vm_pipe.cc.i

vm_pipe.s: vm_pipe.cc.s
.PHONY : vm_pipe.s

# target to generate assembly for a file
vm_pipe.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipe.cc.s
.PHONY : vm_pipe.cc.s

vm_pipeend.o: vm_pipeend.cc.o
.PHONY : vm_pipeend.o

# target to build an object file
vm_pipeend.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipeend.cc.o
.PHONY : vm_pipeend.cc.o

vm_pipeend.i: vm_pipeend.cc.i
.PHONY : vm_pipeend.i

# target to preprocess a source file
vm_pipeend.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipeend.cc.i
.PHONY : vm_pipeend.cc.i

vm_pipeend.s: vm_pipeend.cc.s
.PHONY : vm_pipeend.s

# target to generate assembly for a file
vm_pipeend.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_pipeend.cc.s
.PHONY : vm_pipeend.cc.s

vm_queues.o: vm_queues.cc.o
.PHONY : vm_queues.o

# target to build an object file
vm_queues.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_queues.cc.o
.PHONY : vm_queues.cc.o

vm_queues.i: vm_queues.cc.i
.PHONY : vm_queues.i

# target to preprocess a source file
vm_queues.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_queues.cc.i
.PHONY : vm_queues.cc.i

vm_queues.s: vm_queues.cc.s
.PHONY : vm_queues.s

# target to generate assembly for a file
vm_queues.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_queues.cc.s
.PHONY : vm_queues.cc.s

vm_registers.o: vm_registers.cc.o
.PHONY : vm_registers.o

# target to build an object file
vm_registers.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_registers.cc.o
.PHONY : vm_registers.cc.o

vm_registers.i: vm_registers.cc.i
.PHONY : vm_registers.i

# target to preprocess a source file
vm_registers.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_registers.cc.i
.PHONY : vm_registers.cc.i

vm_registers.s: vm_registers.cc.s
.PHONY : vm_registers.s

# target to generate assembly for a file
vm_registers.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_registers.cc.s
.PHONY : vm_registers.cc.s

vm_run.o: vm_run.cc.o
.PHONY : vm_run.o

# target to build an object file
vm_run.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_run.cc.o
.PHONY : vm_run.cc.o

vm_run.i: vm_run.cc.i
.PHONY : vm_run.i

# target to preprocess a source file
vm_run.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_run.cc.i
.PHONY : vm_run.cc.i

vm_run.s: vm_run.cc.s
.PHONY : vm_run.s

# target to generate assembly for a file
vm_run.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_run.cc.s
.PHONY : vm_run.cc.s

vm_sim.o: vm_sim.cc.o
.PHONY : vm_sim.o

# target to build an object file
vm_sim.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_sim.cc.o
.PHONY : vm_sim.cc.o

vm_sim.i: vm_sim.cc.i
.PHONY : vm_sim.i

# target to preprocess a source file
vm_sim.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_sim.cc.i
.PHONY : vm_sim.cc.i

vm_sim.s: vm_sim.cc.s
.PHONY : vm_sim.s

# target to generate assembly for a file
vm_sim.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_sim.cc.s
.PHONY : vm_sim.cc.s

vm_stack.o: vm_stack.cc.o
.PHONY : vm_stack.o

# target to build an object file
vm_stack.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_stack.cc.o
.PHONY : vm_stack.cc.o

vm_stack.i: vm_stack.cc.i
.PHONY : vm_stack.i

# target to preprocess a source file
vm_stack.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_stack.cc.i
.PHONY : vm_stack.cc.i

vm_stack.s: vm_stack.cc.s
.PHONY : vm_stack.s

# target to generate assembly for a file
vm_stack.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_stack.cc.s
.PHONY : vm_stack.cc.s

vm_thread.o: vm_thread.cc.o
.PHONY : vm_thread.o

# target to build an object file
vm_thread.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_thread.cc.o
.PHONY : vm_thread.cc.o

vm_thread.i: vm_thread.cc.i
.PHONY : vm_thread.i

# target to preprocess a source file
vm_thread.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_thread.cc.i
.PHONY : vm_thread.cc.i

vm_thread.s: vm_thread.cc.s
.PHONY : vm_thread.s

# target to generate assembly for a file
vm_thread.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_thread.cc.s
.PHONY : vm_thread.cc.s

vm_threads.o: vm_threads.cc.o
.PHONY : vm_threads.o

# target to build an object file
vm_threads.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_threads.cc.o
.PHONY : vm_threads.cc.o

vm_threads.i: vm_threads.cc.i
.PHONY : vm_threads.i

# target to preprocess a source file
vm_threads.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_threads.cc.i
.PHONY : vm_threads.cc.i

vm_threads.s: vm_threads.cc.s
.PHONY : vm_threads.s

# target to generate assembly for a file
vm_threads.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_threads.cc.s
.PHONY : vm_threads.cc.s

vm_tools.o: vm_tools.cc.o
.PHONY : vm_tools.o

# target to build an object file
vm_tools.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_tools.cc.o
.PHONY : vm_tools.cc.o

vm_tools.i: vm_tools.cc.i
.PHONY : vm_tools.i

# target to preprocess a source file
vm_tools.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_tools.cc.i
.PHONY : vm_tools.cc.i

vm_tools.s: vm_tools.cc.s
.PHONY : vm_tools.s

# target to generate assembly for a file
vm_tools.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_tools.cc.s
.PHONY : vm_tools.cc.s

vm_type_sizes.o: vm_type_sizes.cc.o
.PHONY : vm_type_sizes.o

# target to build an object file
vm_type_sizes.cc.o:
	$(MAKE) -f CMakeFiles/vm_type_sizes.dir/build.make CMakeFiles/vm_type_sizes.dir/vm_type_sizes.cc.o
.PHONY : vm_type_sizes.cc.o

vm_type_sizes.i: vm_type_sizes.cc.i
.PHONY : vm_type_sizes.i

# target to preprocess a source file
vm_type_sizes.cc.i:
	$(MAKE) -f CMakeFiles/vm_type_sizes.dir/build.make CMakeFiles/vm_type_sizes.dir/vm_type_sizes.cc.i
.PHONY : vm_type_sizes.cc.i

vm_type_sizes.s: vm_type_sizes.cc.s
.PHONY : vm_type_sizes.s

# target to generate assembly for a file
vm_type_sizes.cc.s:
	$(MAKE) -f CMakeFiles/vm_type_sizes.dir/build.make CMakeFiles/vm_type_sizes.dir/vm_type_sizes.cc.s
.PHONY : vm_type_sizes.cc.s

vm_types.o: vm_types.cc.o
.PHONY : vm_types.o

# target to build an object file
vm_types.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_types.cc.o
.PHONY : vm_types.cc.o

vm_types.i: vm_types.cc.i
.PHONY : vm_types.i

# target to preprocess a source file
vm_types.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_types.cc.i
.PHONY : vm_types.cc.i

vm_types.s: vm_types.cc.s
.PHONY : vm_types.s

# target to generate assembly for a file
vm_types.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_types.cc.s
.PHONY : vm_types.cc.s

vm_vm.o: vm_vm.cc.o
.PHONY : vm_vm.o

# target to build an object file
vm_vm.cc.o:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_vm.cc.o
.PHONY : vm_vm.cc.o

vm_vm.i: vm_vm.cc.i
.PHONY : vm_vm.i

# target to preprocess a source file
vm_vm.cc.i:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_vm.cc.i
.PHONY : vm_vm.cc.i

vm_vm.s: vm_vm.cc.s
.PHONY : vm_vm.s

# target to generate assembly for a file
vm_vm.cc.s:
	$(MAKE) -f CMakeFiles/vm_run.dir/build.make CMakeFiles/vm_run.dir/vm_vm.cc.s
.PHONY : vm_vm.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vm_api_test"
	@echo "... vm_run"
	@echo "... vm_type_sizes"
	@echo "... api/vm_api.o"
	@echo "... api/vm_api.i"
	@echo "... api/vm_api.s"
	@echo "... api/vm_api_file.o"
	@echo "... api/vm_api_file.i"
	@echo "... api/vm_api_file.s"
	@echo "... api/vm_api_test.o"
	@echo "... api/vm_api_test.i"
	@echo "... api/vm_api_test.s"
	@echo "... vm_arg.o"
	@echo "... vm_arg.i"
	@echo "... vm_arg.s"
	@echo "... vm_asm.o"
	@echo "... vm_asm.i"
	@echo "... vm_asm.s"
	@echo "... vm_config.o"
	@echo "... vm_config.i"
	@echo "... vm_config.s"
	@echo "... vm_encoding.o"
	@echo "... vm_encoding.i"
	@echo "... vm_encoding.s"
	@echo "... vm_instruction.o"
	@echo "... vm_instruction.i"
	@echo "... vm_instruction.s"
	@echo "... vm_log.o"
	@echo "... vm_log.i"
	@echo "... vm_log.s"
	@echo "... vm_memory.o"
	@echo "... vm_memory.i"
	@echo "... vm_memory.s"
	@echo "... vm_ops.o"
	@echo "... vm_ops.i"
	@echo "... vm_ops.s"
	@echo "... vm_pipe.o"
	@echo "... vm_pipe.i"
	@echo "... vm_pipe.s"
	@echo "... vm_pipeend.o"
	@echo "... vm_pipeend.i"
	@echo "... vm_pipeend.s"
	@echo "... vm_queues.o"
	@echo "... vm_queues.i"
	@echo "... vm_queues.s"
	@echo "... vm_registers.o"
	@echo "... vm_registers.i"
	@echo "... vm_registers.s"
	@echo "... vm_run.o"
	@echo "... vm_run.i"
	@echo "... vm_run.s"
	@echo "... vm_sim.o"
	@echo "... vm_sim.i"
	@echo "... vm_sim.s"
	@echo "... vm_stack.o"
	@echo "... vm_stack.i"
	@echo "... vm_stack.s"
	@echo "... vm_thread.o"
	@echo "... vm_thread.i"
	@echo "... vm_thread.s"
	@echo "... vm_threads.o"
	@echo "... vm_threads.i"
	@echo "... vm_threads.s"
	@echo "... vm_tools.o"
	@echo "... vm_tools.i"
	@echo "... vm_tools.s"
	@echo "... vm_type_sizes.o"
	@echo "... vm_type_sizes.i"
	@echo "... vm_type_sizes.s"
	@echo "... vm_types.o"
	@echo "... vm_types.i"
	@echo "... vm_types.s"
	@echo "... vm_vm.o"
	@echo "... vm_vm.i"
	@echo "... vm_vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

